const SERVICES=[
 {id:'netflix',name:'Netflix',slug:'netflix',tone:'brick'}, {id:'prime',name:'Prime Video',slug:'amazon-prime-video',tone:'blue'},
 {id:'disney',name:'Disney+',slug:'disney-plus',tone:'green'}, {id:'apple',name:'Apple TV+',slug:'apple-tv-plus',tone:'yellow'},
 {id:'max',name:'HBO Max',slug:'hbo-max',tone:'navy'}, {id:'bbc',name:'BBC iPlayer',slug:'bbc-iplayer',tone:'blue'}, {id:'itv',name:'ITVX',slug:'itvx',tone:'green'}
];
const state={service:SERVICES[0],type:'MOVIE',data:null,installPrompt:null};
const els={tabs:document.querySelector('#serviceTabs'),chart:document.querySelector('#chart'),loading:document.querySelector('#loading'),error:document.querySelector('#errorBox'),errorText:document.querySelector('#errorText'),fallback:document.querySelector('#fallbackLink'),chartTitle:document.querySelector('#chartTitle'),sourceLink:document.querySelector('#sourceLink'),sourceBadge:document.querySelector('#sourceBadge'),sourceLabel:document.querySelector('#sourceLabel'),updated:document.querySelector('#updatedText'),refresh:document.querySelector('#refreshBtn'),install:document.querySelector('#installBtn'),sourceNote:document.querySelector('#sourceNote')};
function justWatchUrl(s,t){return `https://www.justwatch.com/uk/provider/${s.slug}/${t==='MOVIE'?'movies':'tv-series'}`}
function dataUrls(){const u=[],m=location.hostname.match(/^([^.]+)\.github\.io$/i),r=location.pathname.split('/').filter(Boolean)[0];if(m&&r)u.push(`https://raw.githubusercontent.com/${m[1]}/${r}/main/data/rankings.json`);u.push('./data/rankings.json');return u}
async function fetchRankings(force=false){let last;for(const base of dataUrls()){try{const res=await fetch(`${base}?v=${force?Date.now():Math.floor(Date.now()/300000)}`,{cache:'no-store'});if(!res.ok)throw new Error(`Ranking feed returned ${res.status}`);const body=await res.json();if(!body?.services)throw new Error('Ranking feed is not ready yet');return body}catch(e){last=e}}throw last||new Error('Ranking feed could not be loaded')}
function initTabs(){SERVICES.forEach(s=>{const b=document.createElement('button');b.className=`service-tab ${s.tone}`;b.type='button';b.textContent=s.name;b.dataset.service=s.id;b.onclick=()=>{state.service=s;document.querySelectorAll('.service-tab').forEach(x=>x.classList.toggle('active',x===b));renderCurrent()};els.tabs.appendChild(b)});els.tabs.firstElementChild?.classList.add('active')}
function posterUrl(raw){if(!raw)return'';if(raw.startsWith('//'))return`https:${raw}`;if(raw.startsWith('/'))return`https://images.justwatch.com${raw}`;return raw}
function normTitle(v=''){return String(v).toLowerCase().replace(/[^a-z0-9]+/g,'')}
function trendText(i){if(!i.trend)return'';const a=Number(i.trendDifference||0);if(i.trend==='UP')return a?`▲ ${Math.abs(a)}`:'▲';if(i.trend==='DOWN')return a?`▼ ${Math.abs(a)}`:'▼';return'—'}
function renderTitles(titles){els.chart.innerHTML='';if(!Array.isArray(titles)||!titles.length)throw new Error('No titles were returned for this chart.');titles.slice(0,10).forEach((item,index)=>{const li=document.createElement('li');li.className=`chart-item accent-${index%4}`;const rank=document.createElement('div');rank.className='rank';rank.textContent=String(index+1).padStart(2,'0');let visual;if(item.poster){const img=document.createElement('img');img.className='poster';img.alt='';img.loading='lazy';img.src=posterUrl(item.poster);img.onerror=()=>{const p=document.createElement('div');p.className='poster poster-placeholder';p.textContent=state.type==='MOVIE'?'🎬':'📺';img.replaceWith(p)};visual=img}else{visual=document.createElement('div');visual.className='poster poster-placeholder';visual.textContent=state.type==='MOVIE'?'🎬':'📺'}const info=document.createElement('div');const title=document.createElement('p');title.className='title';title.textContent=item.title||'Untitled';const meta=document.createElement('p');meta.className='meta';const bits=[item.year,state.type==='MOVIE'?'Movie':'TV series'];if(state.service.id==='netflix'&&state.type==='SHOW'&&item.seasonTitle&&normTitle(item.seasonTitle)!==normTitle(item.title))bits.push(item.seasonTitle);const trend=trendText(item);if(trend)bits.push(trend);if(item.daysInTop10)bits.push(`${item.daysInTop10} ${state.service.id==='netflix'?'wk':'day'}${item.daysInTop10===1?'':'s'} in top 10`);meta.textContent=bits.filter(Boolean).join(' · ');info.append(title,meta);const watch=document.createElement('a');watch.className='watch';watch.textContent='Details ↗';watch.target='_blank';watch.rel='noopener';watch.href=item.url||justWatchUrl(state.service,state.type);li.append(rank,visual,info,watch);els.chart.appendChild(li)})}
function formatUpdated(v){if(!v)return'Waiting for first automatic refresh';const d=new Date(v);if(Number.isNaN(d.getTime()))return'Ranking cache loaded';return`Updated ${new Intl.DateTimeFormat('en-GB',{weekday:'short',day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'}).format(d)}`}
function setLoading(on){els.loading.classList.toggle('hidden',!on);if(on){els.chart.innerHTML='';els.error.classList.add('hidden')}}
function renderCurrent(){const s=state.service,key=state.type==='MOVIE'?'movies':'tv',label=state.type==='MOVIE'?'Movies':'TV Shows',serviceData=state.data?.services?.[s.id],source=serviceData?.sources?.[key],fallbackUrl=justWatchUrl(s,state.type);els.chartTitle.textContent=`${s.name} · Top 10 ${label}`;els.sourceLink.href=source?.url||fallbackUrl;els.sourceLink.textContent='Source ↗';els.sourceBadge.textContent=source?.label||'Source unavailable';els.sourceBadge.className=`source-badge ${source?.kind==='official'?'official':'fallback'}`;els.sourceLabel.textContent=source?.kind==='official'?'UK OFFICIAL TOP 10':'UK POPULARITY';els.sourceNote.textContent=source?.note||'Source details unavailable.';els.fallback.href=source?.url||fallbackUrl;els.error.classList.add('hidden');els.chart.innerHTML='';try{const titles=serviceData?.[key];if(serviceData?.error&&(!titles||!titles.length))throw new Error(serviceData.error);renderTitles(titles);els.updated.textContent=formatUpdated(state.data?.generatedAt)}catch(e){els.errorText.textContent=`${e.message||'This ranking is not available yet'} You can still open the source directly.`;els.error.classList.remove('hidden')}}
async function loadData(force=false){setLoading(true);els.refresh.disabled=true;try{state.data=await fetchRankings(force);renderCurrent()}catch(e){console.error(e);els.errorText.textContent=`${e.message||'The ranking cache could not be loaded.'} The automatic GitHub refresh may not have run yet.`;els.error.classList.remove('hidden');els.updated.textContent='Ranking feed unavailable'}finally{setLoading(false);els.refresh.disabled=false}}
document.querySelectorAll('.segmented button').forEach(b=>b.onclick=()=>{state.type=b.dataset.type;document.querySelectorAll('.segmented button').forEach(x=>x.classList.toggle('active',x===b));renderCurrent()});els.refresh.onclick=()=>loadData(true);window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();state.installPrompt=e;els.install.classList.remove('hidden')});els.install.onclick=async()=>{if(!state.installPrompt)return;state.installPrompt.prompt();await state.installPrompt.userChoice;state.installPrompt=null;els.install.classList.add('hidden')};window.addEventListener('appinstalled',()=>els.install.classList.add('hidden'));if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(console.warn));initTabs();loadData();
