const WATCHLIST_KEY='wozzawatch-my-list-v1';
const listEl=document.querySelector('#myList');
const emptyEl=document.querySelector('#emptyList');
const countEl=document.querySelector('#listCount');

function readList(){try{const x=JSON.parse(localStorage.getItem(WATCHLIST_KEY)||'[]');return Array.isArray(x)?x:[]}catch{return[]}}
function writeList(items){localStorage.setItem(WATCHLIST_KEY,JSON.stringify(items))}
function posterUrl(raw){if(!raw)return'';if(raw.startsWith('//'))return`https:${raw}`;if(raw.startsWith('/'))return`https://images.justwatch.com${raw}`;return raw}
function youtubeTrailerUrl(title){return`https://www.youtube.com/results?search_query=${encodeURIComponent(`${title||'trailer'} trailer`)}`}
function eyeSvg(){return`<svg class="watch-eye-icon" viewBox="0 0 64 36" aria-hidden="true"><path d="M3 18C8 9 14 5 22 5s14 4 19 13c-5 9-11 13-19 13S8 27 3 18Z" fill="none" stroke="currentColor" stroke-width="3.5" stroke-linejoin="round"/><path d="M23 18c5-9 11-13 19-13s14 4 19 13c-5 9-11 13-19 13s-14-4-19-13Z" fill="none" stroke="currentColor" stroke-width="3.5" stroke-linejoin="round"/><circle cx="22" cy="18" r="5" fill="currentColor"/><circle cx="42" cy="18" r="5" fill="currentColor"/></svg>`}
function placeholder(type){return type==='MOVIE'?'<svg class="placeholder-icon" viewBox="0 0 64 64" aria-hidden="true"><path d="M12 24h40v28H12zM11 13.5 48 7l4 11-37 6.5z" fill="currentColor"/><rect x="18" y="32" width="28" height="5" rx="2.5" fill="#eef0fb"/></svg>':'<svg class="placeholder-icon" viewBox="0 0 64 64" aria-hidden="true"><rect x="21" y="5" width="22" height="54" rx="8" fill="currentColor"/><circle cx="32" cy="17" r="4" fill="#eef0fb"/><circle cx="32" cy="46" r="6" fill="none" stroke="#eef0fb" stroke-width="3"/></svg>'}
function render(){const items=readList();listEl.innerHTML='';countEl.textContent=`${items.length} saved`;emptyEl.classList.toggle('hidden',items.length>0);items.forEach((item,index)=>{const li=document.createElement('li');li.className=`chart-item accent-${index%4}`;let visual;if(item.poster){const img=document.createElement('img');img.className='poster';img.alt='';img.loading='lazy';img.src=posterUrl(item.poster);img.onerror=()=>{const p=document.createElement('div');p.className='poster poster-placeholder';p.innerHTML=placeholder(item.type);img.replaceWith(p)};visual=img}else{visual=document.createElement('div');visual.className='poster poster-placeholder';visual.innerHTML=placeholder(item.type)}const a=document.createElement('a');a.className='poster-link';a.href=youtubeTrailerUrl(item.title);a.target='_blank';a.rel='noopener';a.title='Search trailer on YouTube';a.setAttribute('aria-label',`${item.title} — search YouTube for trailer`);a.append(visual);const info=document.createElement('div');info.className='item-info';const title=document.createElement('div');title.className='title';title.textContent=item.title||'Untitled';const meta=document.createElement('div');meta.className='list-meta';meta.textContent=[item.serviceName,item.type==='SHOW'?'TV Show':'Movie'].filter(Boolean).join(' · ');info.append(title,meta);const btn=document.createElement('button');btn.className='watch-toggle active';btn.type='button';btn.innerHTML=eyeSvg();btn.setAttribute('aria-label',`Remove ${item.title} from My List`);btn.title='Remove from My List';btn.addEventListener('click',()=>{writeList(readList().filter(x=>x.key!==item.key));render()});li.append(a,info,btn);listEl.append(li)})}
window.addEventListener('storage',render);
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(console.warn));
render();
