const TYPES={BOOKS:{title:'UK TOP 10 BOOKS',source:'LoveReading',sourceUrl:'https://www.lovereading.co.uk/genres/lrt10/uk-top-10-books'},AUDIOBOOKS:{title:'UK TOP 10 AUDIOBOOKS',source:'Audible',sourceUrl:'https://www.audible.co.uk/charts/best'}};
let active='BOOKS',data={charts:{}};const $=s=>document.querySelector(s);
const WATCHLIST_KEY='wozzawatch-my-list-v1';
const WATCHED_KEY='wozzawatch-watched-v1';
const esc=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function rows(){return data.charts?.[active]||[]}
function searchUrl(title){return active==='BOOKS'?`https://www.amazon.co.uk/s?k=${encodeURIComponent(title)}`:`https://open.spotify.com/search/${encodeURIComponent(title)}`}
function readWatchList(){try{return JSON.parse(localStorage.getItem(WATCHLIST_KEY)||'[]')}catch{return[]}}
function writeWatchList(items){localStorage.setItem(WATCHLIST_KEY,JSON.stringify(items))}
function readId(x){return `read|${active==='AUDIOBOOKS'?'AUDIOBOOK':'BOOK'}|${String(x.title||'').trim().toLowerCase()}`}
function readWatched(){try{return JSON.parse(localStorage.getItem(WATCHED_KEY)||'[]')}catch{return[]}}
function writeWatched(items){localStorage.setItem(WATCHED_KEY,JSON.stringify(items))}
function isSaved(x){const id=readId(x);return readWatchList().some(i=>i.id===id)}
function eyesMarkup(){return '<span class="watch-eyes" aria-hidden="true"><span class="watch-eye"><span class="watch-pupil"></span></span><span class="watch-eye"><span class="watch-pupil"></span></span></span>'}
function earMarkup(){return `<svg class="audio-ear" viewBox="0 0 64 88" aria-hidden="true" focusable="false"><use class="audio-ear-shell" href="ear-icon.svg?v=6.2.3#ear-shell"></use><use class="audio-ear-detail" href="ear-icon.svg?v=6.2.3#ear-detail"></use></svg>`}
function toggleSaved(x,button){let list=readWatchList(),id=readId(x),at=list.findIndex(i=>i.id===id);if(at>=0){const [removed]=list.splice(at,1);const w=readWatched().filter(i=>i.id!==id);w.unshift({...removed,watchedAt:new Date().toISOString()});writeWatched(w);button.classList.remove('saved','pupil-pop');button.setAttribute('aria-pressed','false')}else{list.push({id,title:x.title||'Untitled',poster:x.image||'',service:active==='AUDIOBOOKS'?'WozzaRead · Audiobook':'WozzaRead',serviceId:'read',type:'BOOK',readKind:active==='AUDIOBOOKS'?'AUDIOBOOK':'BOOK',author:x.author||'',addedAt:new Date().toISOString()});button.classList.add('saved');button.classList.remove('pupil-pop');void button.offsetWidth;button.classList.add('pupil-pop');setTimeout(()=>button.classList.remove('pupil-pop'),700);button.setAttribute('aria-pressed','true')}writeWatchList(list)}
function animateTab(type){const b=document.querySelector(`.read-tab[data-read-type="${type}"]`);if(!b)return;b.classList.remove('read-animate');void b.offsetWidth;b.classList.add('read-animate');setTimeout(()=>b.classList.remove('read-animate'),720)}
function render(){
 const meta=TYPES[active],r=rows();$('#readTitle').textContent=meta.title;document.body.classList.toggle('read-audio-mode',active==='AUDIOBOOKS');document.querySelectorAll('.read-tab').forEach(b=>b.classList.toggle('active',b.dataset.readType===active));
 const badge=$('#readSourceBadge');if(badge){const src=data.sources?.[active]||meta.sourceUrl;badge.href=src;badge.textContent=`STATS FROM ${meta.source.toUpperCase()}`;badge.setAttribute('aria-label',`Stats from ${meta.source} — open source`)}
 $('#readChart').innerHTML=r.slice(0,10).map((x,i)=>{const art=x.image?`<a class="read-cover-link" href="${esc(searchUrl(x.title))}" target="_blank" rel="noopener noreferrer" aria-label="Search ${esc(x.title)} on ${active==='BOOKS'?'Amazon UK':'Spotify'}"><img class="poster read-cover" src="${esc(x.image)}" alt="${esc(x.title)} cover"></a>`:`<a class="read-cover-link" href="${esc(searchUrl(x.title))}" target="_blank" rel="noopener noreferrer" aria-label="Search ${esc(x.title)} on ${active==='BOOKS'?'Amazon UK':'Spotify'}"><span class="poster read-cover read-cover-fallback">W</span></a>`;const save=`<button class="watch-toggle read-watch-toggle${active==='AUDIOBOOKS'?' audiobook-ear-toggle':''}${isSaved(x)?' saved':''}" data-read-save="${i}" type="button" aria-pressed="${isSaved(x)}" aria-label="${isSaved(x)?'Remove':'Add'} ${esc(x.title)} ${isSaved(x)?'from':'to'} Watchlist">${active==='AUDIOBOOKS'?earMarkup():eyesMarkup()}</button>`;return `<li class="read-row has-watch-toggle"><span class="rank">${String(i+1).padStart(2,'0')}</span>${art}<span class="read-copy"><strong>${esc(x.title)}</strong><small>${esc(x.author||'')}</small></span>${save}</li>`}).join('');
 document.querySelectorAll('[data-read-save]').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();const x=r[+b.dataset.readSave];if(x)toggleSaved(x,b)}));$('#readError').classList.toggle('hidden',r.length===10)
}
async function load(){try{const res=await fetch('./read.json?v='+Date.now(),{cache:'no-store'});if(!res.ok)throw Error(res.status);data=await res.json();const d=data.updated?new Date(data.updated):null;$('#readUpdated').textContent=d&&!Number.isNaN(d.valueOf())?'Updated '+d.toLocaleDateString('en-GB',{weekday:'short',day:'numeric',month:'short'})+', '+d.toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'}):'Latest UK charts'}catch(e){console.error('WozzaRead load failed',e);data={charts:{}}}render()}
function setReadType(type){if(!TYPES[type]||type===active){animateTab(type);return}active=type;render();animateTab(type)}function toggleReadType(){setReadType(active==='BOOKS'?'AUDIOBOOKS':'BOOKS')}
document.querySelectorAll('.read-tab').forEach(b=>b.addEventListener('click',()=>setReadType(b.dataset.readType)));
function initReadGestures(){const target=$('.read-chart-wrap');if(!target)return;let sx=0,sy=0,tracking=false,lastTap=0,lastX=0,lastY=0;target.addEventListener('touchstart',e=>{if(e.touches.length!==1)return;const t=e.touches[0];if(t.clientX<24||t.clientX>innerWidth-24)return;sx=t.clientX;sy=t.clientY;tracking=true},{passive:true});target.addEventListener('touchend',e=>{if(!tracking||e.changedTouches.length!==1)return;tracking=false;const t=e.changedTouches[0],dx=t.clientX-sx,dy=t.clientY-sy,ax=Math.abs(dx),ay=Math.abs(dy);if(ax>=55&&ax>ay*1.2){toggleReadType();lastTap=0;return}if(ax>16||ay>16||e.target.closest('a,button'))return;const now=Date.now(),close=Math.hypot(t.clientX-lastX,t.clientY-lastY)<42;if(lastTap&&now-lastTap<=330&&close){lastTap=0;toggleReadType();return}lastTap=now;lastX=t.clientX;lastY=t.clientY;setTimeout(()=>{if(Date.now()-lastTap>=330)lastTap=0},340)},{passive:true});target.addEventListener('touchcancel',()=>tracking=false,{passive:true});target.addEventListener('dblclick',e=>{if(!e.target.closest('a,button'))toggleReadType()})}
function initMenu(){const menu=$('#wozzaMenu'),bd=$('#wozzaMenuBackdrop'),trigger=$('.header-copy');let timer=null,start=null;const open=()=>{menu.classList.add('open');menu.setAttribute('aria-hidden','false');bd.hidden=false};const close=()=>{menu.classList.remove('open');menu.setAttribute('aria-hidden','true');bd.hidden=true};trigger?.addEventListener('click',open);bd?.addEventListener('click',close);$('.wozza-menu-back')?.addEventListener('click',close);$('#wozzaMenuList')?.addEventListener('click',e=>{let b=e.target.closest('[data-href]');if(b)location.href=b.dataset.href});document.addEventListener('pointerdown',e=>{if(e.target.closest('a,button,.wozza-menu'))return;start={x:e.clientX,y:e.clientY};timer=setTimeout(()=>{if(start&&start.x>innerWidth*.2&&start.x<innerWidth*.8&&start.y>innerHeight*.2&&start.y<innerHeight*.8)open()},350)});document.addEventListener('pointermove',e=>{if(start&&Math.hypot(e.clientX-start.x,e.clientY-start.y)>12){clearTimeout(timer);timer=null}});['pointerup','pointercancel'].forEach(n=>document.addEventListener(n,()=>{clearTimeout(timer);timer=null;start=null}))}
initMenu();initReadGestures();load();
