import fs from 'node:fs/promises';
const BOOKS_URL='https://www.lovereading.co.uk/genres/lrt10/uk-top-10-books';
const AUDIO_URL='https://www.audible.co.uk/charts/best';
const headers={'User-Agent':'Mozilla/5.0 (compatible; WozzaRead/5.3.42)','Accept':'text/html,application/xhtml+xml'};
const decode=s=>String(s||'').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;|&apos;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&#(\d+);/g,(_,n)=>String.fromCharCode(+n)).replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim();
async function html(url){const r=await fetch(url,{redirect:'follow',headers});if(!r.ok)throw Error(`${r.status} ${url}`);return r.text()}
function jsonLdProducts(src){const out=[];for(const m of src.matchAll(/<script[^>]+type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi)){try{const j=JSON.parse(m[1]);const walk=x=>{if(!x)return;if(Array.isArray(x))return x.forEach(walk);if(typeof x==='object'){if(/Book|Product/i.test(x['@type']||'')&&x.name)out.push(x);Object.values(x).forEach(walk)}};walk(j)}catch{}}return out}
function booksFromHtml(src){let products=jsonLdProducts(src).map(x=>({title:decode(x.name),author:decode(Array.isArray(x.author)?x.author.map(a=>a.name||a).join(', '):(x.author?.name||x.author||'')),image:Array.isArray(x.image)?x.image[0]:(x.image?.url||x.image||'')})).filter(x=>x.title);if(products.length>=10)return products.slice(0,10);
 // LoveReading's public chart is rendered as ten ordered book cards. Capture title/author from common heading/card patterns.
 const area=(src.match(/UK Top 10 Books[\s\S]{0,180000}/i)||[src])[0];const headings=[...area.matchAll(/<h[2-4][^>]*>([\s\S]*?)<\/h[2-4]>/gi)].map(m=>decode(m[1])).filter(Boolean);const blacklist=/UK Top 10|bestsell|newsletter|recommend|review/i;const titles=headings.filter(x=>!blacklist.test(x));const unique=[...new Set(titles)];return unique.slice(0,10).map(title=>({title,author:'',image:''}))}
function audibleFromHtml(src){const chunks=[...src.matchAll(/<li[^>]*class=["'][^"']*productListItem[^"']*["'][^>]*>([\s\S]*?)<\/li>/gi)].map(m=>m[1]);let rows=chunks.map(c=>{const rank=(decode((c.match(/<h3[^>]*>([\s\S]*?)<\/h3>/i)||[])[1]).match(/^(\d+)\./)||[])[1];const h=decode((c.match(/<h3[^>]*>([\s\S]*?)<\/h3>/i)||[])[1]).replace(/^\d+\.\s*/,'');const by=decode((c.match(/By:\s*<\/span>\s*<a[^>]*>([\s\S]*?)<\/a>/i)||c.match(/By:\s*([^<\n]+)/i)||[])[1]);const nar=decode((c.match(/Narrated by:\s*<\/span>\s*([\s\S]*?)<\/li>/i)||[])[1]).split('Length:')[0];const img=(c.match(/<img[^>]+src=["']([^"']+)["']/i)||[])[1]||'';return {rank:+rank,title:h,author:by,narrator:nar,image:img}}).filter(x=>x.rank&&x.title).sort((a,b)=>a.rank-b.rank);if(rows.length>=10)return rows.slice(0,10).map(({rank,...x})=>x);
 // Fallback to the explicit numbered headings Audible exposes server-side.
 rows=[...src.matchAll(/<h3[^>]*>(?:\s*<[^>]+>)*\s*(\d+)\.\s*([\s\S]*?)<\/h3>/gi)].map(m=>({rank:+m[1],title:decode(m[2]),author:'',narrator:'',image:''})).filter(x=>x.rank<=10).sort((a,b)=>a.rank-b.rank);return rows.map(({rank,...x})=>x)}
let previous={charts:{}};try{previous=JSON.parse(await fs.readFile('read.json','utf8'))}catch{}
const next={updated:new Date().toISOString(),charts:{...previous.charts},sources:{BOOKS:BOOKS_URL,AUDIOBOOKS:AUDIO_URL}};let changed=false;
for(const [key,url,parser] of [['BOOKS',BOOKS_URL,booksFromHtml],['AUDIOBOOKS',AUDIO_URL,audibleFromHtml]]){try{const rows=parser(await html(url));if(rows.length!==10||rows.some(x=>!x.title))throw Error(`expected exactly 10 ranked titles, got ${rows.length}`);next.charts[key]=rows;changed=true;console.log(`${key}: verified 10`)}catch(e){console.warn(`${key}: ${e.message}; retaining previous verified chart`);if(!next.charts[key]?.length)console.warn(`${key}: no previous chart available`)}}
if(!changed&&Object.keys(next.charts).length===0)throw Error('No WozzaRead charts could be verified');await fs.writeFile('read.json',JSON.stringify(next,null,2)+'\n');
